### ISSUE TITLE
linux系统下C++示例运行点云信息错误

### ISSUE THREAD

**Issue by yaohaihang1** [Open3DV/Xema#32]
linux下cpp_example，在开机后运行示例，点云会出现三角形的面片形状
![image](https://github.com/Open3DV/Xema/assets/117330523/d15ca1f8-1408-43bd-8365-182393b897b3)
![image](https://github.com/Open3DV/Xema/assets/117330523/d8a88e39-1d6d-4912-927b-19372acef3ae)

**Comment by zhangguanjin** [comment]
排查发现XEMA::captureBrightnessData(unsigned char* brightness, XemaColor color) 功能在一些参数下与int XEMA::captureData(int exposure_num, char* timestamp)采集点云功能有冲突。单独采集亮度图时光机投影了6张灰度图，实际只需要一张，曝光时间大的时候，会影响到后续的点云重建条纹投影。但该bug不是上述现象的原因。

**Comment by zhangguanjin** [comment]
分析现场相机，发现其固件不是正式版本的固件，而是一个中间版本。固件更新成v1.5.2固件后，问题解决。
