### ISSUE TITLE
相机上电后出现光机iic通信异常

### ISSUE THREAD

**Issue by xqlong5121** [Open3DV/Xema#33]
xema-s-500w（basler）相机，上电出现光机挂掉
核心板，载板，光机，驱动板，IIC线依次更换过测试，还是会出现上电后光机挂掉的问题
光机挂掉后，连接到ti软件可以正常投影。
概率：50%，偶现能复现
![img_v3_0075_2d3491d9-3fa7-4677-971d-4272f296248g](https://github.com/Open3DV/Xema/assets/117330250/5f38ca78-6e50-4cf3-9480-804b901b46d8)
![img_v3_0275_6b24c920-5dc0-4d90-ac93-a464f45ca54g](https://github.com/Open3DV/Xema/assets/117330250/ac594b18-931f-42d7-8aca-9eb5ace1cd70)

**Comment by xqlong5121** [comment]
一台1805-200w相机，上电也出现了光机挂掉现象
光机挂掉后连接ti软件投影是正常的
![K0Kl5KSvx1](https://github.com/Open3DV/Xema/assets/117330250/d8bff2a6-f04c-4d31-8876-2b0a2070b895)

**Comment by xqlong5121** [comment]
出现异常时，reboot软重启无法恢复，断电重启可概率恢复

**Comment by xqlong5121** [comment]
多次测试发现：
1、断电间隔10s以内大概率出现异常
2、断电间隔＞15s，25次断电，两台相机都正常启动，无异常
3、快速拔插：使用示波器监测，启动会出现短暂的iic通信
4、间隔15s以上启动：使用示波器监测：启动不会出现iic通信

**Comment by vic-w** [comment]
对iic的SDA和SCL两条线进行观察，发现上电瞬间，光机的iic口会向外发出一串命令，随后如果SDA保持“拉低”，则会进入异常状态。
而拉低实际上是jetson nano板子在拉低，如果断开jetson nano和光机的iic连线，光机这端的SDA和SDL在发完那一串命令之后就会释放变高。

**Comment by vic-w** [comment]
怀疑是载板上测温芯片的iic异常导致SDA被拉低。焊掉这颗芯片确实不会拉低。
但再次焊上，仍不会出现拉低。似乎板子被修复了。

**Comment by vic-w** [comment]
测温芯片是MCP3221再次验证：

**Comment by SpermWhale42** [comment]
经讨论，认为是最新批次的载板来料概率不良问题，不属于硬件设计问题。

最新批次载板所用测温芯片报废，出测试报告，反馈贴片厂商，协商返厂。临时需求使用上批次库存物料，补充测试后出厂。

**Comment by SpermWhale42** [comment]
经讨论，认为是最新批次的载板来料概率不良问题，不属于硬件设计问题。

最新批次载板所用测温芯片报废，出测试报告，反馈贴片厂商，协商返厂。临时需求使用上批次库存物料，补充测试后出厂。
