### ISSUE TITLE
大恒相机usb丢帧问题

### ISSUE THREAD

**Issue by yaohaihang1** [Open3DV/Xema#35]
大恒相机500w在运行时会存在丢帧的问题，现对寄存器的值在规定范围内进行了修改，发现问题没有改善。
1、GUI或者程序连续运行时，无丢帧现象。
2、杀camera_server再次运行，无丢帧现象
2、软重启再采集，无论怎样修改寄存器的值都会出现丢帧，必现

现进行断电重启测试，如果断电重启没有问题，那就可以证明软重启的过程，对相机的初始化等造成了丢帧

**Comment by SpermWhale42** [comment]
大恒相机稳定性存在问题，收益有限，大恒相机选型pending，主要精力投放在海康相机选型上。
