### ISSUE TITLE
The PCB production files

### ISSUE THREAD

**Issue by rgruberski** [Open3DV/Xema#5]
Hi! Where can I find PCB production files? Do you share some Gerber files or direct links to PCB manufacture? I would like to make a PCB, with assembly if possible. Can I buy the PCB directly from you? Thank you in advance.

**Comment by vic-w** [comment]
https://github.com/Open3DV/xema_hardware/tree/main/pcb

**Comment by vic-w** [comment]
https://github.com/Open3DV/xema_hardware/tree/main/pcb

**Comment by rgruberski** [comment]
I tried to use the Pads software but the current version of the Pads Pro Browser is incompatible with the project version and can't import the PCB file. The error "The selected design file is not a valid .pcb file". It is possible to open the layout with the PADS Layout Viewer, but it doesn't have an option for exporting the project to Gerber files.

**Comment by vic-w** [comment]
Hi，rgruberski. I updated the xema_hardware repository. the Gerber file is added to the pcb folder. Please check them here in https://github.com/Open3DV/xema_hardware/tree/main/pcb

**Comment by vic-w** [comment]
You can purchase all the components for a 3D camera from this [Taobao link](https://item.taobao.com/item.htm?spm=a1z10.1-c.w137644-24671353601.40.546b701f2a4Y79&id=694002907610). If you need to create your own circuit board, you can try using this online platform [Seeed Fusion PCB Assembly Service](https://www.seeedstudio.com/pcb-assembly.html)
